#!/usr/bin/env python3
import time


DOBBY = """
                                                                -:::=++-:::-                            
                                        -::::=++*++-:::-    -:%*-...:::::...+@-:                        
                                  -:#*:.:.:::.:.:::::::=@%#:..:-::::::::::::::.@=-                     
                              --::#:.:::::.=#:::::::=*%%*::::@=:::::@%------:::::.@:                    
                          --*..:+::-@#*##+.::::::%=::::::::::::#+:*:------@:::===-:@-                   
                        -*.:..::.#.:::=#@@@@@@*:::::::::::::::::@.:::#--=#-+-:   --                    
                        -:*##+::::=:**:.:::::::::::::::::%*:::::::%.:@----::%-                          
                    :-#-...::::::::@:::::::::@:::::::::::::@.*@@@@@@#----%:=-                           
                ::%-...:::::::::::@.::::::::@:::::::::::::@    @@*@@@@:*-::+:                           
            -:#...:::::::::::::::::::::::*@@@*-:::::--::+.   @@+ .@@@+::::#:                           
          :-+.:::.+#+.::::::::::::::::-*@@@@@@@@+::-:-:---  @@@@@@@@@=::::@-                           
        -+-.::.%=----@::::::::::::@@=   %@+:@@@@@%::::+::@. *##%%%@@#---:@:                            
        :*..:.%-:---:-*::::::::::::+.    .@  @@@@@@=:::::@@-@@@%@@@%@@@@@--    +-  -#-                  
      :=.:::=+----=@=-%::.:::::--::@     @@@@@@@%@%*:::--:::::--:::-::-#*: --  :*  -+  :@-              
    -+..:.@:----=*-----:--::::::::=-    .@%%%%@@#%=:-----::::::-:=%@@:-   :@:         -- :@            
    =.::::::::::=+--==@:::::-::---:%. @@@@@%%@=@@#:=::+@@@@@%*==-=-=-  ==: :@@+:::...:   --            
    -::::::::::::-@--===@::::::::::::-@@@%%%@%@@@--:@-::::@@-:------@:   --:@-@#@.@.%.@%#- #*-          
  :#.::::=@@%%-:--#:=--=@:--::----:::::-%@@@%=:::-:::::::::--------+      =-:%*@.@.#:@:+.--:-          
  =.::%*:-   --#::-:=@*@%---::-----:::-:-----:----::+@@#--:-::::--@-     :+-:@.:.:.....@:  -           
  -=::         :@.:::--::-::------------------------@#:-@-:---::=+-    -+=::@.:..::::..@-              
                  :@::-----::------:-:-::::-::-----::-@--+--:-:-@:    -=@::-@@..@+:-@:::=               
                    :%#-:::-:::::-%=:--::::---------:-@-::*:=@*:   --@+:::%+:@...@.@:::+:               
                      -:+@@@@@%:  .+@-::::::-:----::-@-::%:@*=+%@%--:::@+- :%:::::...:#:               
                          :@%-:-#@%**-@-:@@@+#*#+=---#@--==-@-=-----*@+:    :=:.:::::::--:              
                        -+=-#..:.+@:.@..:%@:%%#+#@@=@-::@--@++=-::-        -:..:::::::::+@-:           
                        =@.....+@+@-@%:-@=:.@..=@--@=-::@-..@:              =@@@.:::::::::.:+@:         
                          -----#-%-:%::@::::+#%%+-:::.@+::::*:              *%@@*::::::::@@%%%@=        
                              -@:@..@:-*@=:::::::::#@-:+%:..--              -@@@=.::::..@@%%%%@%        
                              +:%.@: +=.@.:+++*=-:.::::.%+:.*               =-%#::.:...@@%%%%%-        
                              -=:@:  *=.:@..@::@..-@..::.::.@-                  =::+@@=@@#%@%:         
                                =   -%-:::@::-@:=.::@:.@+::.@-                                         
                                    -@::::.@::..:.:::++-.:::%:                                         
                                    -@-:::@::@:::::::.:@.:::+:                                         
                                    :@-::.*::.::::::::::=+:::-                                         
                                    :+-::::#::::%-..::::..::.#                                         
                                    =:-:::.@:::::-#:::::::::.@-                                        
                                    :%:=-::.+:::::::@:::::::::@-                                        
                                    :#--:.::.:::::::.:.....:.:@:                                        
                                    -=@%-=#@@#@=..:..-@@=-@@@%%-                                        
                                          -:%+%::::::::#-#:                                             
                                          +####+     -@####%#%#-=                                       
                                        -######-    -############=                                     
                                        =*#######+   =###########%=                                     
                                        -@######%=   =##########%=                                      
                                        -::-=-:=                                                       
"""


def run_ls_demo() -> None:
    print("\n\n\n")
    print("One of the most important spells you need to know is `ls` (or lumos).")
    time.sleep(3)
    print("`ls` lights up a room so you can see what's in it.")
    time.sleep(3)
    print("Run `ls` when you are in a location and need to see what you can interact with.")
    time.sleep(3)
    print("\n\n")
    print("Let's say you want to see what files/folders/programs you can interact with.")
    time.sleep(3)
    ls_cmd = input("What would you type? ")
    while ls_cmd != 'ls':
        ls_cmd = input("Not quite.... let's try that again: ")
    print("\n\n\n")
    print("Excellent!")
    print("Don't be shy running `ls`, it can help re-orient you and figure out a room.")
    time.sleep(3)
    print("I hope that helps!")
    time.sleep(3)


def run_file_demo() -> None:
    print("\n\n\n")
    print("One of the most important spells you need to know is `cat`.")
    time.sleep(3)
    print("`cat` reads a file so you can know what it says.")
    time.sleep(3)
    print("Run `cat` when encounter a **white** file and want to read it.")
    time.sleep(3)
    print("\n\n")
    print("Let's say you see a **white** file named `hello.txt`")
    time.sleep(3)
    cat_cmd = input("What would you type to read it? ")
    while cat_cmd != 'cat hello.txt':
        cat_cmd = input("Not quite.... let's try that again: ")
    print("\n\n\n")
    print("Excellent!")
    print("Remember, anytime you see a **white** file, think of your trusy cat.")
    time.sleep(3)
    print("I hope that helps!")
    time.sleep(3)


def run_program_demo() -> None:
    print("\n\n\n")
    print("One of the most important things you can do is run programs.")
    time.sleep(3)
    print("Programs are **green** and you run them by typing `./PROGRAM_NAME`.")
    time.sleep(3)
    print("\n\n")
    print("Let's say you see a **green** program named `fun_game`.")
    time.sleep(3)
    program_cmd = input("What would you type to run it? ")
    while program_cmd != './fun_game':
        program_cmd = input("Not quite.... let's try that again: ")
    print("\n\n\n")
    print("Excellent!")
    print("Remember, anytime you see a **green** file, think of trying to run it.")
    time.sleep(3)
    print("I hope that helps!")
    time.sleep(3)


def run_directory_demo() -> None:
    print("\n\n\n")
    print("One of the most important spells you need to know is `cd`.")
    time.sleep(3)
    print("`cd` allows your to change your current directory - kind of like")
    print("changing the door to walk into a new room.")
    time.sleep(3)
    print("Run `cd` when encounter a **blue** folder/directory and want to go into it.")
    time.sleep(3)
    print("\n\n")
    print("Let's say you see a **blue** folder named `homework`")
    time.sleep(3)
    cat_cmd = input("What would you type to go into the folder? ")
    while cat_cmd != 'cd homework':
        cat_cmd = input("Not quite.... let's try that again: ")
    print("\n\n\n")
    print("Excellent!")
    print("Remember, anytime you see a **blue** folder/directory, think of `cd`.")
    time.sleep(3)
    print("I hope that helps!")
    time.sleep(3)


def run_dobby() -> None:
    print(DOBBY)
    time.sleep(3)
    print("Hello Harry!")
    print("\n")
    time.sleep(1)
    print("I'm here to help if you have any questions.")
    print("\n\n\n")
    time.sleep(3)
    print('Do you need help? Type "yes" if you do, "no" if you do not.')
    help_needed_answer = ""
    while help_needed_answer.lower() not in ["yes", "no"]:
       help_needed_answer = input("Your answer: ")

    if help_needed_answer.lower() == "no":
        print("\n")
        print("Ok, just come find me if you need help!")
        print("\n")
        time.sleep(3)
        return

    while True:
        time.sleep(1)
        print("\n")
        print("Q: What do you need help with:")
        print("   A: What do do first")
        print("   B: What to do with files (white)")
        print("   C: What to do with programs (green)")
        print("   D: What to do with folders/directories (blue)")
        print("   E: I don't need any more help")
        print("\n")

        multi_answer = input("Your answer: ")
        if multi_answer.lower() == "a":
            run_ls_demo()
        elif multi_answer.lower() == "b":
            run_file_demo()
        elif multi_answer.lower() == "c":
            run_program_demo()
        elif multi_answer.lower() == "d":
            run_directory_demo()
        elif multi_answer.lower() == "e":
            break
        else:
            print("I'm sorry, I didn't understand that.")


if __name__ == "__main__":
    run_dobby()
