#!/bin/python3
import time
import typing


CONDUCTOR = """
          @@@@@@@@@@@@@@@@@@@@@@@@@
        @@   .:-----------------:  @@
      @@ --------------------------- %@
     @@.------------------------------ @@
     @@+++++++++++++++++--------------++@+
    @@@@@@@@@@@@@@@@@@@@@@@*+=--------++@%
  @@------------------------@@++----++++@*
*@--------------------------++@+++++++++@*
@#+++++++++++++++++++++++++++++@++++++++@
 %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    +@###%@@@@@:::::@@@%################@#
    #@#@................:%@@@@@##########@@
   #@@%@..................:::@###########@@
     @%@.:@..........@@....:@##@@@######%%@@
    @%%@...................:@@@::-@#####%%%%@@
    @@#@...................:::::::@##%%%%%%@
     @%@...................:::::+@@%%%%%%%%%@
    @@%@#.................::::@%%%%%%%%%%%@@@@
    @%%%@+................::::@%%%%%%%%%@%%@
    @@%%%@@@-::::::::::::::-@@@%%%%%%%%%@%@@@
    @@@@@@++%@##%%%%%%%%@*=@@::+@@@% #@@%
         @@--@######%%@@@=@:::====+@
        @@=@--@##%%%@@--@@::::@====#@
       #@==@--#@@@@@-----@@::::=====@#
       @@@@@-@@------@----@@:::-@@@@@@
      @@===@-%@------@----=@*-::-=====@
      @@@@@@-+@-----*@----+@@@@@@@@@@#@
      %@:::@-----------=@@@@.....::::*@
       @:::@%---------@=---@@@:..::::@#
       @@+@-+@-------@-----@++++++%@@@
        @%@---#@#----@-----#@#++++++@#
          @-------#@@@-------++@@@@
          @------=+++@-------+++++@
          @------++++@-------+++++@
          @+++++++###@++++++*#%%@@@
          @#########@@############@
         @@@@@@@@@@@@@@@@@@@@@@@@@@
"""

def text_question_correct(question: str, answer: str) -> bool:
    time.sleep(3)
    print("\n\n\n")
    print("Q: " + question)
    print("\n")

    response = input("Your answer: ")
    if response.lower() == answer:
        print("Impressive!")
        return True
    else:
        print("Your professors should be ashamed!")
        return False


def choice_question_correct(question: str, options: typing.Dict[str, str], answer: str) -> bool:
    time.sleep(3)
    print("\n\n\n")
    print("Q: " + question)
    for option in sorted(options):
        question = options[option]
        print("   {}: {}".format(option, question))
    print("\n")

    response = input("Your answer: ")
    if response.lower() == answer.lower():
        print("Impressive!")
        return True
    else:
        print("Your professors should be ashamed!")
        return False


def question_one_correct() -> bool:
    return text_question_correct("What color are directories?", "blue")


def question_two_correct() -> bool:
    return text_question_correct("What color are programs?", "green")


def question_three_correct() -> bool:
    return choice_question_correct(
        "What is the general format of a spell?",
        {
            "A": "OPTIONAL_FILE SPACE COMMAND (e.g., `./note.txt cat` and `ls`)",
            "B": "COMMAND NO_SPACE OPTIONAL_FILE (e.g., `cat./note.txt` and `ls`)",
            "C": "COMMAND SPACE OPTIONAL_FILE (e.g., `cat ./note.txt` and `ls`)",
            "D": "COMMAND SPACE ALWAYS_FILE (e.g., `cat ./note.txt` and `ls ./note.txt`)",
        },
        "C",
    )


def question_four_correct() -> bool:
    return choice_question_correct(
        "When do you need to put a `./` in front of something?",
        {
            "A": "When you're lonely",
            "B": "When the thing you want to interact with is in the same dir as you",
            "C": "When you want to go back to the beginning",
            "D": "When you have run out of options",
        },
        "B",
    )


def run_conductor() -> None:
    print(CONDUCTOR)
    time.sleep(3)
    print("Trying to get on the train without paying???")
    time.sleep(3)
    print("You're going to have to earn your way on by answering me these questions four")

    if not question_one_correct():
        return

    if not question_two_correct():
        return

    if not question_three_correct():
        return

    if not question_four_correct():
        return

    print("\n\n\n")
    print("Ok, I guess you earned your way. You can get on the train to hogwarts")
    print("Execute the spell `sl` and good luck!")
    time.sleep(5)


if __name__ == "__main__":
    run_conductor()

