#!/usr/bin/env python3
import time
import typing


CONDUCTOR = """
          @@@@@@@@@@@@@@@@@@@@@@@@@
        @@   .:-----------------:  @@
      @@ --------------------------- %@
     @@.------------------------------ @@
     @@+++++++++++++++++--------------++@+
    @@@@@@@@@@@@@@@@@@@@@@@*+=--------++@%
  @@------------------------@@++----++++@*
*@--------------------------++@+++++++++@*
@#+++++++++++++++++++++++++++++@++++++++@
 %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    +@###%@@@@@:::::@@@%################@#
    #@#@................:%@@@@@##########@@
   #@@%@..................:::@###########@@
     @%@.:@..........@@....:@##@@@######%%@@
    @%%@...................:@@@::-@#####%%%%@@
    @@#@...................:::::::@##%%%%%%@
     @%@...................:::::+@@%%%%%%%%%@
    @@%@#.................::::@%%%%%%%%%%%@@@@
    @%%%@+................::::@%%%%%%%%%@%%@
    @@%%%@@@-::::::::::::::-@@@%%%%%%%%%@%@@@
    @@@@@@++%@##%%%%%%%%@*=@@::+@@@% #@@%
         @@--@######%%@@@=@:::====+@
        @@=@--@##%%%@@--@@::::@====#@
       #@==@--#@@@@@-----@@::::=====@#
       @@@@@-@@------@----@@:::-@@@@@@
      @@===@-%@------@----=@*-::-=====@
      @@@@@@-+@-----*@----+@@@@@@@@@@#@
      %@:::@-----------=@@@@.....::::*@
       @:::@%---------@=---@@@:..::::@#
       @@+@-+@-------@-----@++++++%@@@
        @%@---#@#----@-----#@#++++++@#
          @-------#@@@-------++@@@@
          @------=+++@-------+++++@
          @------++++@-------+++++@
          @+++++++###@++++++*#%%@@@
          @#########@@############@
         @@@@@@@@@@@@@@@@@@@@@@@@@@
"""

def text_question_correct(question: str, answer: str) -> bool:
    time.sleep(3)
    print("\n\n\n")
    print("Q: " + question)
    print("\n")

    response = input("Your answer: ")
    if response.lower() == answer:
        print("Impressive!")
        return True
    else:
        print("Your professors should be ashamed!")
        return False


def choice_question_correct(question: str, options: typing.Dict[str, str], answer: str) -> bool:
    time.sleep(3)
    print("\n\n\n")
    print("Q: " + question)
    for option in sorted(options):
        question = options[option]
        print("   {}: {}".format(option, question))
    print("\n")

    response = input("Your answer: ")
    if response.lower() == answer.lower():
        print("Impressive!")
        return True
    else:
        print("Your professors should be ashamed!")
        return False


def question_one_correct() -> bool:
    return text_question_correct("What color are directories/folders?", "blue")


def question_two_correct() -> bool:
    return choice_question_correct(
        "What is the correct way to cast the `cat` spell?",
        {
            "A": "`./note.txt cat`",
            "B": "`cat./note.txt` (i.e. no space between `cat` and the file)",
            "C": "`cat ./note.txt` (i.e. space between `cat` and the file)",
        },
        "C",
    )


def question_three_correct() -> bool:
    return text_question_correct("What color are programs?", "green")


def question_four_correct() -> bool:
    return choice_question_correct(
        "How would you apparate to hogsmeade?",
        {
            "A": "cd hogsmeade",
            "B": "cd ./hogsmeade",
            "C": "cd ..",
            "D": "cd /hogsmeade",
        },
        "D",
    )


def run_conductor() -> None:
    print(CONDUCTOR)
    time.sleep(3)
    print("Trying to get on the train without paying???")
    time.sleep(3)
    print("You're going to have to earn your way on by answering these four questions")

    if not question_one_correct():
        return

    if not question_two_correct():
        return

    if not question_three_correct():
        return

    if not question_four_correct():
        return

    print("\n\n\n")
    print("Ok, I guess you earned your way. You can get on the train to hogwarts")
    print("Execute the spell `sl` and good luck!")
    time.sleep(5)


if __name__ == "__main__":
    run_conductor()

