#!/usr/bin/env python3
import os
import time

DUMBLEDORE = """
                                     . .............:::............
                              ......:############################*+.......
                              .##############%%%###*###*###%%#########*:.
                         ...#######%#####################################+..
                       ..#############################################*%###.
                     ..%####%###############################################...
                     .=####*#################################################..
                     =-####*--############----*############----##########-###..
                     .--%####-*###########----=####=--=####----#########*--###.
                      .---###*#=--------+##*+*##---------*###*##*-------**=###.
                        -=###----------------------------------------------###=..
                       .=####***##############################***++==-------###..
                       .-=############################################***###%##..
                        :-#########%%%%%%%%%%%%%%%%%%%%%%%%%###################=.
                        .:##+=%##----------------------------------------***%%#..
                       .:###==##=----------------------------------------##+=##.
                       .:##==+##-----------------------------------------##*==##.
                      .:##*==+##-----------------------------------------+##==##.
                      :=##===+##-----------------------------------------=#*===##.
                     .:##+===+##----=+==----------------------------------#*===##.
                     :###====+##---#########++---------------=#*#######---##====#*
                    .:##+====##=--------#######+-----------+#######%#=----##====##.
                    .##*====*##--------------------------------------------#*====#*.
                  ..###====*###--------------------------------------------##*===##.
                  .###====#####------@@@@@#---------------------@@@@#=----*###+===%#.
                ..##+===+###=##*----+@@@@@@#-------------------@@@@@@@----##+-##*==##:.
               ..##+==+###*===##=----@@@@@@------+*****+++------@@@@@#---+##==+##++=*#
               =##*=+###%#*===*#*------@@=---*#####===-=%###++---=@*-----##===##=##+=##.
               -##*###@@+##====%#*--------=###*============-%##+--------##+===##*@*#*##.
               :##*====@@##=====*##+=---*##%========+#*=======-##++--=###=====##@===##..
               .:###=====##+======*######+=====++*###=##+*+**====*#####======+##====##.
               .:###=====*##===================-========-##==================##+====##.
              ..###+======##=================================================##=====-#*.
             ..###========%#*===============================================*#*=======##.
            .-##*==========#*+=============================================+##========##*
             -###===========#**===========================================##%========###.
             .###*===========%#**======================================+###=========+##.
              .*##+============###*++===============================*####===========##..
               .##*===============+####+*+=====================+#*###+@@=========+###..
                .=##++============@@+++##*###*+***+=====+***#####++++++@*===*#*####.
                 ..:####*++*+=====@@++++++@@++*%###=====##%++++@*++++++@%####=.. .
                      ...+####++*#@+++++++*@++++**=####*=#*++++@+++++++%@..
                              .##@@++++++++@+++##***#====##++++@#%%%%@@@@=
                              .:+@@@@@@@@@@@+++##=+=+#====##+++@@@@*+=#@*.
                               ..#@%=--@@@+++++##========+##+++++#@@@@@%.
                                ..+@@@@@#++++++##*=======##+++++++++@@.
                                 .--%@++++++++++##+====+##=+++++++++#@.
                                 .--@@++++++++++++##*=*##++++++++++++@=.
                                .---@*+++++++++++++%###++++++++++++++@@.
                                 --@@+++++++++++++++++++++++++++++++*%@.
                                .:-@@*#%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@.
                                 ..@@@@@@@@@@@@@@@@@@-%@@@@@@@@@@@%-.
                                     ..=%@@@%##**++===---:::::.....
                                        ..... .    . .
"""


class bcolors:
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    ENDC = '\033[0m'


def run_dumbledore_intro() -> None:
    print(DUMBLEDORE)
    time.sleep(3)
    print("Hello Harry!")
    print("We need your help, there's two monsters blocking passage to the school!")
    print("Without them removed, we'll be on summer break forever!!!")
    time.sleep(7)
    print("\n\n\n")
    print("The monsters will need some special spells to defeat them.")
    print(f"Next to me is a spell book called {bcolors.BOLD}spell_book.txt{bcolors.ENDC}... use it learn new spells.")
    print(f'To **search** for a particular spell, do {bcolors.UNDERLINE}grep "PHRASE" spell_book.txt{bcolors.ENDC}')
    time.sleep(15)
    print("\n\n\n")
    print("Let's try an example now!")
    print("\n\n\n")
    time.sleep(3)
    print(f"Let's say you want to find all instances of \"hello\" in the {bcolors.BOLD}spell_book.txt{bcolors.ENDC} file")
    time.sleep(3)
    grep_cmd = input("What would you type? ")
    while grep_cmd != 'grep "hello" spell_book.txt':
        grep_cmd = input("Not quite.... let's try that again: ")

    print("\n\n\n")
    print("Excellent!")
    print('One pattern I know will be quite helpful is "Tab Complete"')
    print(f'Search for it in the spell book by doing {bcolors.UNDERLINE}grep "Tab Complete" spell_book.txt{bcolors.ENDC}')
    time.sleep(15)
    print("Once you're done defeating both monsters, come see me for your prize!")
    time.sleep(5)
    print("Good luck Harry!")
    time.sleep(3)


def run_dumbledore_outro() -> None:
    print(DUMBLEDORE)
    time.sleep(3)
    print("Harry!!! I knew you could do it!")
    time.sleep(3)
    print("Now it's time to claim your prize")
    time.sleep(3)
    print("1. Make sure your volume is on")
    print("2. Open up a new terminal (Applications/Utilities/Terminal)")
    print(f"3. Run the spell {bcolors.UNDERLINE}say I won give me candy Mr Rizzi{bcolors.ENDC}")
    time.sleep(3)


def run_dumbledore_so_close() -> None:
    print(DUMBLEDORE)
    time.sleep(3)
    print("Harry, you're so close! Just one more trial to go!!!")
    time.sleep(3)


if __name__ == "__main__":
    # monster_1_alive = os.path.isfile("/var/hogwarts_castle/back_gate/monster.txt")
    back_gate_done = True
    front_door_done = os.path.isfile("/var/hogwarts_castle/front_door/monster_friend.txt")

    if not back_gate_done and not front_door_done:
        run_dumbledore_intro()
    elif not back_gate_done or not front_door_done:
        run_dumbledore_so_close()
    else:
        run_dumbledore_outro()

